// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctxgnnjvnkowccvyywgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0eGdubmp2bmtvd2Njdnl5d2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDIwNTgsImV4cCI6MjA3MDIxODA1OH0.h9PMF0YDbrwMGGtpKNQ_rPMbp6Ff6YdHmfzI_DTcPYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});